# version: "3.9"

services:
  db:
    image: postgres
    container_name: db_cp
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: service_center
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
      TZ: Europe/Moscow
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/service_center"
    volumes:
      - .:/app

  storage:
    image: minio/minio
    ports:
      - "9000:9000"  # Порт для доступа к MinIO
      - "9001:9001"  # Порт для веб-консоли
    environment:
      MINIO_ACCESS_KEY: file_server
      MINIO_SECRET_KEY: file_server_secret
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data  # Хранение данных MinIO

volumes:
  data:
  minio_data:
